### ISSUE TITLE
Fehlermeldung bei der F-16 der NTF

### ISSUE THREAD

**Issue by StephanPe** [BAVerrecus/NTF-Modset#10]
![20171123234408_1](https://user-images.githubusercontent.com/33942849/33190811-6375c01e-d0b1-11e7-82dc-9f40670e2dcd.jpg)
Bug: 
Beim setzen einer F-16 von der NTF kommt beim neu laden der Mission im Editor eine Fehlermeldung

Wo: 
NTF Addons , nur im Editor getestet

Reproduzierbar: 
Ja   z.B   F-16CJ 13th FS  ,  F-16C Polish  ,  F-16D Blank    wurde getestet und der Fehler ist ausgetreten. Daher der verdacht das er bei denn anderen F-16 auch auftritt.

Beschreibung: 
eine F-16 der NTF setzen → Mission Speichern → eine andere Mission öffnen → jetzt wieder die Mission mit der F-16 laden → Fehlermeldung

Zusatz:
Falls der Fehler bekannt ist sry ….aber melden macht frei und belastet den Vorgesetzten

**Comment by BAVerrecus** [comment]
Dieser Fehler ist bekannt.
Er tritt auf mit der F-16 (auch mit der originalen) wenn TFAR mindestens Version 1.0 mitgeladen wird.
Die F-16 hat im Cockpit einen Display für die eingestellte Frequenz des im Flugzeug verbauten Funkgeräts. Das funktioniert aber nur mit max Version 0.9.12.
Also zusammengefasst: leider nicht fixbar von meiner Seite her.
