### ISSUE TITLE
MEV M113 - Einladen von bewustlosen Personen

### ISSUE THREAD

**Issue by wurschtl12** [BAVerrecus/NTF-Modset#12]
In der Mission am 24.11.2017 wurde oben genanntes Fahrzeug verbaut. Es war den Medics nicht möglich, bewustlose Personen über ACE einzuladen.

**Comment by BAVerrecus** [comment]
kann nicht reproduziert werden.
ich lass das issue offen und werde es weiter beobachten.

**Comment by BAVerrecus** [comment]
es sind jetzt 4 monate vergangen. mir wurde nicht nochmal darüber berichtet. außerdem stehen mit den spaniern jetzt auch alternativen für die rhs m113 zur verfügung. deshalb closed.
