### ISSUE TITLE
MEV M113 - Einsteigen auf den Kommandantensitz

### ISSUE THREAD

**Issue by wurschtl12** [BAVerrecus/NTF-Modset#13]
In der Mission am 24.11.2017 war es nicht möglich, von außen direkt auf den Kommandantensitz einzusteigen. Zu dem Zeitpunkt hat keine weitere Person versucht einzusteigen.
Auch ein erneutes Öffnen und Schließen der Luke hat nicht geholfen.
Ich musste in den Schützenraum und von dort auf den Kommandantensitz.

**Comment by BAVerrecus** [comment]
kann nicht reproduziert werden.
ich lass das issue offen und werde es weiter beobachten.

**Comment by BAVerrecus** [comment]
es sind jetzt 4 monate vergangen. mir wurde nicht nochmal darüber berichtet. außerdem stehen mit den spaniern jetzt auch alternativen für die rhs m113 zur verfügung. deshalb closed.
