### ISSUE TITLE
"Uunfold Map" - Karte wird für den Besitzer der Karte nicht auf den Boden gelegt

### ISSUE THREAD

**Issue by Stehwahn** [BAVerrecus/NTF-Modset#15]
Bug+Beschreibung: 
Im Ace-Selbst Interaktionsmenü "Unfold Map" auswählen -> Karte wird auf den Boden gelegt.
Die Karte wird für denjenigen, der den Befehl durchführt nicht angezeigt. Karte verschwindet aus Inventar.
Alle anderen Mitspieler können die Karte sehen/öffnen/aufheben

Betroffen: Addons-Modset

Reproduzierbar? Ja

**Comment by BAVerrecus** [comment]
der mod ist komplexer als erwartet. ich hab auch noch nicht sicher rausgefunden wo im code der hund begraben ist (zwar eine vermutung, aber nicht mehr). muss da noch mehr herumspielen und stelle das issue erstmal hinten an, da dieser mod ohnehin eher selten wirklich genutzt wird.

**Comment by BAVerrecus** [comment]
fehler nicht behebbar meinerseits. mod wurde aus modset entfernt. ich behalte ihn noch ime auge, bin aber nebenbei auch noch dabei etwas eigenes zu modden.
