### ISSUE TITLE
DAC - Fehlermeldung 

### ISSUE THREAD

**Issue by Armaopterix** [BAVerrecus/NTF-Modset#18]
Die Fehlermeldung wird von der .pbo im Ordner Scripts --> DAC_Group_Soldier.sqf hervorgerufen. Siehe dazu auch Screenshot. 

![20171208140910_1](https://user-images.githubusercontent.com/33845530/33767876-06db5d04-dc24-11e7-9afd-6b47243c41bc.jpg)

In der Zeile 26 steht folgendes:

_newgroup = group player;_rankarray = ["private","corporal","sergeant","lieutnant","captain","major","colonel"];

Richtig wäre aber: 

_newgroup = group player;_rankarray = ["private","corporal","sergeant","lieutenant","captain","major","colonel"];

Der Fehler liegt ganz klar beim Rang lieutnant den es lt. [BI Wiki](https://community.bistudio.com/wiki/rank) nicht gibt. Richtig wäre eben lieutenant

Deswegen wirft Zeile 235 auch den Fehler aus.

Zeile 235:
_eman allowFleeing _setFleeing;_eman setRank _setrank;

LG
Martin

**Comment by Armaopterix** [comment]
Die Funktionsweise ist von der Fehlermeldung nicht beeinträchtigt. Es wird vermute ich direkt ein anderer Rang zugewiesen. Die Meldung spuckt er trotzdem aus.

Spawn und Despawn der Einheiten funktioniert, auch im Kampf arggieren sie normal.

**Comment by Armaopterix** [comment]
![00036bc589a161e01dfeec040c06d181](https://user-images.githubusercontent.com/33845530/33768269-a6e0372e-dc25-11e7-998a-024ccecaa986.png)

Der Skill wird bei den Einheiten auch zugewiesen und verändert. Also scheint es wirklich nur den Rang zu betreffen.

**Comment by Armaopterix** [comment]
Ich habe weiter getestet heute über den halben Tag:

1. Es werden Ränge vergeben, alle Einheiten der Gruppe werden in der Definierten Größe die man vorgibt gespawnt. Es fehlt einfach nur der lieutenant rang. 
2. Ich habe mehrere Änderungen in den Config's mehrere Änderungen vorgenommen, um wirklich zu sehen ob Skill und alles in den vorgegebenen Sachen übernommen wird, klappt wunderbar.
3. Habe längere Zeit gewartet beim Despawnen um sie dann wieder Spawnen zu lassen. Auch hier gibt es die Fehlermeldung nicht erneut. 
4. Die KI verhält sich wunderbar im Kampf, wechselt auch ihr Kampfverhalten bei Feindbeschuss, auch da scheint die KI keine Probleme zu machen. 

Weiß nicht ob dir die Infos helfen, ich schreibe sie dir hier einfach mal rein! :) 

LG
Martin

**Comment by Armaopterix** [comment]
Hallo B.A.,

wie in Whats App Geschrieben habe ich mir die rpt bei mir angesehen. Es handelt sich um die Script Variante von DAC und das Spawnen von reiner INfanterie.

[arma3_x64_2017-12-09_15-43-27.txt](https://github.com/BAVerrecus/NTF-Modset/files/1545049/arma3_x64_2017-12-09_15-43-27.txt)

Der Fehlerteil:

if(isNil "DAC_AI_Count_Level")	then {>
16:21:49   Error position: <};
if(isNil "DAC_AI_Count_Level")	then {>
16:21:49   Error Missing ]
16:21:49 File C:\Users\marti\Documents\Arma 3 - Other Profiles\Vogelgrippchen\missions\Reshman\[NM]Operation-Wild-Ghost.reshmaan\DAC\DAC_Config_Creator.sqf, line 24
16:21:49 Error in expression <s24","s25","s26","s27","s28","s29","s30"};
if(isNil "DAC_AI_Count_Level")	then {>
16:21:49   Error position: <};
if(isNil "DAC_AI_Count_Level")	then {>
16:21:49   Error Missing ]

War mein Fehler, als ich einen Fehler in der DAC_Config_Creator.sqf. Ich hatte dort einfach die ] vergessen. Den Fehler kannst du also ausblenden. 

DAC erscheint nicht mehr in der RPT. Die Fehler die im BI Forum sind, konnte ich nicht reproduzieren. 

Ich habe allerdings in der Script Variante auch die DAC_Group_Soldier.sqf angepasst wie oben beschrieben. So kam der Fehler nie mehr beim Spawnen und Despawnen der Einheiten. 

Im BI Forum schreibt der Kollege etwas von der Zeile 463 in der DAC_Create_Groups.sqf 

Alle anderen Beiträge im BI Forum beziehen sich im übrigens auf vor dem Update. 

LG
Martin

**Comment by Armaopterix** [comment]
Da ich mehrfach probiert habe, die Fehlermeldungen vom Forum nicht bei mir aufplobben und ich nur mit Infanterie 0 Probleme habe auch die RPT gut aussieht. Werde ich eine Testmission machen mit DAC. Die Mission am 06. 

Wie gesagt, ich habe dac zisch mal durchlaufen lassen und diese Meldungen kommen bei reiner INfanterie nicht bei mir, egal wie oft ich mich weg geportet habe etc. 

Ich nutze für die Testmission aber die Scriptvariante, weil ich da den Fehler manuell beheben konnte.

**Comment by Armaopterix** [comment]
ich möchte dir einen kurzen Zwischenstand zu DAC geben. Werde es im Github nochmal Posten. Gestern bei der Testversion hatte ich DAC aktiviert (Script Variante) der HC war aus und DAC hat perfekt funktioniert. Patroullien wurden erzeugt, Wegpunkte haben funktioniert, KI hat super Reagiert und unter einander Kommuniziert und die FPS der Spieler waren durchweg ohne Performnace Einschränkungen. Auch de Server FPS waren zwischen 38 und 46. 

Wichtig ist dabei, das der HC komplett deaktiviert ist bzw. in den Addon Options. Dann werden auch Wegpunkte und alles ordentlich erzeugt. Meine Script DAC Datei hänge ich im GITHUB an :) 

LG
Martin

**Comment by Armaopterix** [comment]
[DAC18_02_2018.zip](https://github.com/BAVerrecus/NTF-Modset/files/1734614/DAC18_02_2018.zip)

**Comment by BAVerrecus** [comment]
bis auf die script fehlermeldung, die man mit den configs fixen kann, sind keine fehler reprudozierbar bzw die die reproduzierbar sind, sind anwenderfehler.
deshalb erstmal closed.
sollte wieder was gefunden werden, bitte einen neuen thread eröffnen.
