### ISSUE TITLE
Towing von Vanilla Flugzeugen

### ISSUE THREAD

**Issue by TimoNTF** [BAVerrecus/NTF-Modset#19]
Das Towing mit Lesh Tow funktioniert aktuell nur mit bestimmten Vanilla Flugzeugen. Bei diesen Flugzeugen sieht man auch keinen gelben Punkt der den Tow Punkt anzeigt.

Folgende Flugzeuge lassen sich nicht towen (Fehlermeldung: "Tagret vehicle not in range") :
F/A-181 Black Wasp II
V-44 X Blackfish
To-201 Shikra (Tarn)
A-149 Gryphon

Bei der To-201 Shikra tritt die Fehlermeldung"No suitable vehicles nearby" auf.

Ich habe auch alle Vanilla Helikopter mit Räder getestet. Diese funktionieren alle ohne Probleme.

**Comment by BAVerrecus** [comment]
towing einstellungen für die black wasp sind jetzt vorhanden.
issue bleibt weiter offen da die anderen flugzeuge noch fehlen.
außerdem müssen die koordinaten für die fir flugzeuge dringend überarbeitet werden.

**Comment by BAVerrecus** [comment]
jetzt sollten alle flugzeugen funzen, da die lesh einträge bei den parent klassen gemacht wurden. sollte ein flugzeug nicht funzen, bitte neuen eintrag erstellen.
