### ISSUE TITLE
Panzerrauch

### ISSUE THREAD

**Issue by BAVerrecus** [BAVerrecus/NTF-Modset#2]
Ein Modkonflikt scheint den Vanilla Fahrzeugrauchwerfer zu stören und damit auch alle Fahrzeugrauchwerfer die ihre Config daraus beziehen.

**Comment by JayJay2288** [comment]
Ich habe die Mods mal einzeln geladen, bzw nach einander deaktiviert.
Raus kommt das im Ordner @ntf_add_ad die PBO "warfxpe_edited" dran schuld ist.
Löscht man sie, funktioniert es wieder.
MfG JayJay

**Comment by JayJay2288** [comment]
Update:
die BW-Mod hat auch ein Rauch problem. Zwar werden hier die BW-Mod Rauchpatronen verschossen, aber dieser "Kurzzeitrauch" bildet sich auch hier direkt am Fhz.

Die Artillerie hat ebenfalls ein Rauch Problem. Die Treffer im Ziel bzw der Rauch erscheint nur sporadisch. Gefühlt jeder 2 Schuss erzeugt falschen oder gar keinen Nebel.

**Comment by TimoNTF** [comment]
Bei dem Pizarro Panzer der Spanier Mod sehen Schützen und Fahrer den Smoke nicht, alle anderen, auch Teile außerhalb des Panzers, sehen ihn.

**Comment by BAVerrecus** [comment]
mit dem nächsten update wird das alles gefixt sein, die blastcore version wird ausgetauscht.

der fehler mit dem pizzaro lässt sich allerdings weder mit dem derzeitigen noch mit dem geupdateten modset reproduzieren.
