### ISSUE TITLE
Bugreport BAF Coyote P HMG

### ISSUE THREAD

**Issue by NTFSamsung** [BAVerrecus/NTF-Modset#20]
Wie auf dem Bild ersichtlich, dreht sich das aufgebaute Visier nicht mit der Waffe mit.

https://www.pic-upload.de/view-34484338/20171216220431_1.jpg.html

**Comment by BAVerrecus** [comment]
fehler confirmed und 100% reproduzierbar. dürfte an einer falschen named selection im model liegen, dh nicht von meiner seite aus fixbar. die modmacher kennen den fehler und er wird mit dem nächsten update der mod behoben sein.
