### ISSUE TITLE
Bordfunkgerät Helikopter Fehlerhaft

### ISSUE THREAD

**Issue by IIcRaShII** [BAVerrecus/NTF-Modset#22]
In der Heutigen Mission, mit dem Vanilla Helikopter, funktionierte das Bordfunkgerät auf keiner eingestellten Frequenz, weder senden noch empfangen.

**Comment by TimoNTF** [comment]
Lag wohl daran das der Heli Independent und die Spieler Funkgeräte Blufor waren

**Comment by BAVerrecus** [comment]
mission nochmal geprüft, der fehler war vom missionsbauer, es war genau das was timo beschrieben hat.
