### ISSUE TITLE
SMA SCAR-H Anzeigefehler

### ISSUE THREAD

**Issue by Ch3y** [BAVerrecus/NTF-Modset#24]
Bei der SMA SCAR-H werden Reservemagazine in der Munitionsanzeige doppelt angezeigt.

![bu](https://user-images.githubusercontent.com/35468395/34960382-e0f54228-fa3a-11e7-9b98-c7ee3b2c3d62.jpg)

- Addons Modset
- Tritt in Arsenal, Editor und auf dem Server auf.

**Comment by BAVerrecus** [comment]
bestätigt. weiß aber noch nicht woran das liegt. hatte das früher schonmal irgendwo bei ner mod, weiß aber auswendig nicht mehr woran es lag. ich werd mal tiefer eintauchen.

**Comment by BAVerrecus** [comment]
gefixt mit dem april update.
