### ISSUE TITLE
Kollision zwischen NTF Add-Ons und Rolling Thunder 23 Modset

### ISSUE THREAD

**Issue by wurschtl12** [BAVerrecus/NTF-Modset#25]
Wenn man über Steam/Arma Launcher das Rolling Thunder Modset (Steam Workshop) und alle zugehörigen Mods, siehe [Video Ortac](https://www.youtube.com/watch?v=qQNs6qoRUKc&list=PLc2KLIpR6wf4QenakSxA_n2QKUnfLyXb1), herunterlädt und anschließend über Just Sync das NTF Add-Ons Modset starten will, dann kommt es zu folgender Fehlermeldung:

![fehler](https://user-images.githubusercontent.com/33969344/35239213-24d754ac-ffb0-11e7-8ef0-e59e50d012c7.png)

**Comment by BAVerrecus** [comment]
das ganze ist etwas komisch, denn eigentlich dürfte das nicht passieren. workshop mods werden woanders gespeichert als unser modset. trotzdem scheint es so als würde die workshop version von rhs unsere version überschreiben. ich muss mir das genauer ansehen, nicht nur wegen dem event, sondern weil es so scheint als würde das update von rhs meine kompabilitäts pbo zerschiessen...

**Comment by wurschtl12** [comment]
Ok mach das :) Du wolltest ja einen Screenshot haben, deswegen hab ich das gepostet.

**Comment by BAVerrecus** [comment]
ich weiß mittlerweile WAS kaputt gegangen ist, ich weiß nur nicht WARUM. 
da sich aber rolling thunder erstmal erledigt hat wird das issue geschlossen und erst wieder aufgegriffen wenn eine erneute einladung zu einem event das ein steam ws modset nutzt ansteht.
