### ISSUE TITLE
Fehler auf Lythium FFAA

### ISSUE THREAD

**Issue by JulianGreenGhost** [BAVerrecus/NTF-Modset#26]
in der nähe von Mafaraz in der Militärbasis stehen 3 Schleppdach Unterstände diese explodieren bei geringem Beschuss (etwa 2-3 Magazine g36)

Gruß Julian

**Comment by Stehwahn** [comment]
Ich habe mir das ganze einmal angesehn: 
Alle JBAD "Sheds" haben das Problem - ich brauchte z.T. nur 2-3 Schuss und ein Schuppen explodiert.

Ich vermute, dass es daran liegt, dass in der CfgVehicles der entsprechenden Gebäude ein großzügiger Wert von 150 für die Armor gewählt wurde - Zum Vergleich: der selbe Schuppen in der Vanilla-Ausführung hat einen Wert von 2000.

**Comment by BAVerrecus** [comment]
es ist genau das was stehwahn geschrieben hat. alle jbad buildings haben im grunde dieses problem, bei manchen ist es auffälliger als bei anderen.
dass es aussieht als würde das ganze explodieren liegt an den gebäude zerstörungs partikel effekten von blastcore und fehler in der config der gebäude in denen sowas wie zelte oder marktstände als gebäude definiert wurden und dementsprechend die selben zerstörungseffekte haben wie gebäude.

theoretisch lässt sich das mit einer zusätzlichen config lösen, allerdings müssten dann alle jbad buildings überarbeitet werden und das ist mir dann doch zu viel arbeit. sollte jemand dazu motivation finden ist er natürlich herzlich dazu eingeladen das zu machen und an mich weiterzuleiten! bis dahin ist das hier erstmal closed...
