### ISSUE TITLE
F-16 Afterburner funktioniert nicht 

### ISSUE THREAD

**Issue by Plato0** [BAVerrecus/NTF-Modset#27]
**Modset:** NTF Addons 
**getestet:** Im Editor, auf selbst gehosteten server
**Reproduzierbar:** JA 

Sobald man in irgendeine der NTF F16's versucht den Afterburner zu benutzten erscheind folgende Fehlermeldung 
![20180128050839_1](https://user-images.githubusercontent.com/35884176/35479015-57a3f918-03ec-11e8-880f-4c2d9c4e42d1.jpg)

Nach dieser Fehlermeldung löst der Afterburner nicht aus dass, heißt kein sound und kein geschwindigkeits schub.

Schritte zum Reproduzieren 

1. Irgendeine der NTF F16's unter Blufor\NATO\Planes\ auswählen und im Editor platzieren 

2. Einsteigen und den Afterburner Aktivieren

LG  Platoo

**Comment by BAVerrecus** [comment]
passiert das bei allen f16?
bitte wenn möglich ALLE f16 testen. ich hab einen verdacht worans liegt, kann das aber leider frühestens donnerstag selber überprüfen...

**Comment by Plato0** [comment]
So nach ausführlichen testen ist das Ergebnis dass, bei allen F16's die das NTF Logo haben funktioniert er nicht bei den mit dem Firewill Logo funktioniert er.
Was mir auch noch aufgefallen ist bei den NTF F16's das Targeting System nicht geöffnet werden kann, wenn der Targeting pod ausgerüstet ist.

![20180128163645_1](https://user-images.githubusercontent.com/35884176/35484059-8e763920-044a-11e8-8df6-764dd3f3d8fd.jpg)
![20180128163706_1](https://user-images.githubusercontent.com/35884176/35484060-8e97cf22-044a-11e8-9e97-0cf795d790fd.jpg)

**Comment by BAVerrecus** [comment]
okay thx fürs testen. dann liegt es daran was ich erwartet habe. beide fehler. wird mit dem nächsten modset update gefixt sein, jetzt weiß ich woran es liegt und sollte ne arbeit von 10 minuten sein...

**Comment by Plato0** [comment]
Danke B.A !

**Comment by BAVerrecus** [comment]
vorerst gefixt im 02.18 update
