### ISSUE TITLE
Behandlung von Patienten in Helikoptern

### ISSUE THREAD

**Issue by TimoNTF** [BAVerrecus/NTF-Modset#28]
Aktuell kann man in Helikoptern keine anderen Personen behandeln. Dies tritt im Singleplayer und Multiplayer (Server) auf. Schuld daran ist die PBO rwrmod.pbo (http://www.armaholic.com/page.php?id=32193) im Ordner @ntf_add_ad. Dies tritt nur mit dem Addons Modset auf. Nach Starten des Modsets ohne diese PBO funktioniert alles wie es funktionieren soll. 

Danke an Morello fürs Testen.

**Comment by BAVerrecus** [comment]
rwr mod kommt raus bis ich geschafft habe zu fixen dass dieser mod immer die erste ace option ausschaltet...
