### ISSUE TITLE
Modvorschlag HAFM EC-635 Helicopter

### ISSUE THREAD

**Issue by Plato0** [BAVerrecus/NTF-Modset#30]
Hallo B.A und NTF Community 

Ich habe mich jetzt auch mal hingesetzt, um einen Modvorschlag zu schreiben
probieren kostet ja nichts.

**1.) Um welchen Mod handelt es sich? (Bitte mit Link)**
Bei den Mod handelt es sich um den Eurocopter-635 von Aplion.
**Armaholic:** http://www.armaholic.com/page.php?id=28903
**Steam:** http://steamcommunity.com/sharedfiles/filedetails/?id=1137757814
**BI Forum:** https://forums.bohemia.net/forums/topic/182146-hafm-ec-635-helicopter/

**2.) Hast du den Mod selber getestet?**
Ja 

**2.a) Wenn ja, gibt es Bugs?**
Nach Ausführlichem testen habe ich nichts gefunden, die Bugs die in den Foren bei anderen Usern auftreten konnte ich nicht Reproduzieren.

**3.) Hast du den Mod zusammen mit unserem Modset getestet?**
Ja mit dem Addons Modset.

**3.a) Wenn ja, gibt es Bugs?**
siehe 2.a)

**4.) Welche Requirements hat der Mod?**
Keine 

**4.a) Haben wir diese Requirements im Modset? (Wenn "nein" gilt es die Fragen nochmal extra für den benötigten Mod auszufüllen)**
siehe 4)

**5.) Welchen Mehrwert hätte es diesen Mod aufzunehmen?**
Der Eurocopter hat viele Einsatzmöglichkeiten bei uns in der NTF nicht nur hätten wir wieder einen Transport Hubschrauber für die Bundeswehr sondern auch leichten CAS.

Den Eurocopter gibt es auch nicht nur in der BW Variante, sondern auch im Simplen Schwarz als CSAT oder zivil und mit Funktionierenden Slingload, Wärmebildkamera und firing from vehicles ist er bestens geeignet um viele verschiedene Rollen im Feld einzunehmen.

**6.) Wie häufig schätzt du die Nutzung des Mods ein?**
Mittelmäßig bis Oft.

**7.) Hast du dich in Foren über Fehler und Probleme mit diesem Mod informiert?**
siehe 2.a)

**7.a) Wenn ja, was ist das Ergebnis?
siehe 2.a)** 

**8.) Welche Szenarien könntest du dir mit diesem Mod vorstellen? (wenn es sich um einen Mod handelt der immer wirkt bzw. Gameplaymechaniken permanent ändert, ist diese Frage zu ignorieren)**
Wie schon bei 5) Angesprochen CAS, MEDEVAC und Transport.

**9.) Was gefällt dir besonders gut an dem Mod?**
Wenn ich ehrlich bin kann ich nicht genau eine Sache festmachen, ich mag halt alles was fliegt und
das es ein BW Heli ist macht die Sache noch besser.

**10.) Was gefällt dir nicht an diesem Mod?**
Der Sound ist komisch und hier und da mal ein paar Matsch Texturen außerdem, erstellt der Mod eine Zweite BW Fraktion unter der vom BW Mod.

**11.) Warum willst du gerade diesen Mod und nicht einen mit vergleichbarem Inhalt (wenn es denn einen gibt)?**
Es gibt keinen Vergleichbaren Mod.

So das war es auch 
Danke fürs Lesen.

Lg Platoo

**Comment by BAVerrecus** [comment]
1. Der Heli wurde released und danach nie wieder geupdatet. der release war im sommer 2015, das sind fast 3 Jahre ohne Update!
2. Der Heli hat keine ACE comp
3. Alle im BI Forum beschriebenen Bugs sind noch immer vorhanden.

sry, aber nein
