### ISSUE TITLE
Brille Kaputt. Style Gefährdet

### ISSUE THREAD

**Issue by Sno01** [BAVerrecus/NTF-Modset#32]
Die Quadratische Sonnenbrille ist seit einiger Zeit defekt.

Alle Spieler die diese Brille verwenden sehen folgendes: https://steamuserimages-a.akamaihd.net/ugc/930429967301908078/FD6F2FF894983D292BA1FE1AEB62D9495DE462CD/

Bitte Mr. B.A. Retten sie unseren Style! Es ist unmöglich ein anderes Modell zu nutzen als dieses. 

Das Problem besteht bei diversen Kopf Skins. Ich bin nicht der einzige den es betrifft. 
Es betrifft wohl auch andere Brillen getestet habe ich die beiden Quadratischen Brillen. 

Lg Sno in Not

**Comment by Sno01** [comment]
Update: Besagte Brille war in Chey's Mission vom 24.03.2018 "Welcome in the Zone" Fehlerfrei.

**Comment by BAVerrecus** [comment]
es wirkt also so als würde das ganze nicht an den brillen liegen sondern an entweder helm, uniform oder westen. das hilft schonmal weiter

**Comment by BAVerrecus** [comment]
weißt du was du an hattest oder in welcher mission auf welchem slot das mit der brille passiert ist?

**Comment by Sno01** [comment]
Wie schon gesagt das Bild oben zeigt eine Blufor Nato Einheit (Überlebender) Ohne jegliche Ausrüstung auf Tanoa. Es ist nur ein Zeus Modul verbaut.

Zusatzinfos zu Cheys mission. 

Map: Chenarus
Einheit: Wiederstand
Rolle: Medic (Slot 4 Stalker)

Ich habe etwas Rumgespielt und konnte den "Fehler" in Cheys Mission Manuel herbeiführen indem ich meine Uniform ausgezogen habe. Instand erschien die Brille wieder im Sichtfeld. 

Als ich mir am Ausrüster das Loadout erneut gezogen habe verschwand sie wieder.  
Neuer Hinweis daher Uniformen. Ich habe gezielt stück für stück alle Ausrüstung abgelegt und die Uniform beim zweiten mal als letztes ausgezogen.  Und beim dritten mal habe ich das Inventar komplett geleert und dann ganz am Ende die Uniform abgelegt. 

Fazit: Es ist die Uniform die den Fehler irgendwie behoben hat. zusätzlich habe ich die anderen Loadouts der Stalker gecheckt und auch hier das selbe.   

Uniformen:
 M88 (Tan?
Guerilla Coveralls (Napa 02) 
Guerilla Coveralls (Napa 03)
Guerilla Coveralls (Napa/Prizrak)

Ich denke das hilft dir weiter.

**Comment by Sno01** [comment]
Hiermal die Classnames der Uniformen im Arsenal. 

https://steamuserimages-a.akamaihd.net/ugc/929305210770389895/2B0958F5E94F079C2008004AC120C873081140DF/

https://steamuserimages-a.akamaihd.net/ugc/929305210770389767/04ED73282AB042EEAC81DE27E15043E30F78939A/

https://steamuserimages-a.akamaihd.net/ugc/929305210770389621/91F6A61F46BDBB10D89E780787DA7C50C0673F24/

https://steamuserimages-a.akamaihd.net/ugc/929305210770389416/991F540FD15F1CD3E217B2E2A1D1F24D3F442F40/


Ich habe danach ein paar Uniformen Random getestet, und es ist sehr unterschiedlich welche gehen und welche nicht. Zunächst dachte ich man kann es auf eine Unit Mod beschränken, aber bei RHS zum Beispiel gehen manche, und manche nicht. Das ist ein etwas aufwendigerer test der Länger dauern könnte. Und ich bin nicht sicher ob es weiterhilft herauszufinden, welche Units das Problem immer haben und welche nicht und welche gemischt. Falls ich ein Muster finde lasse ich es dich wissen.

**Comment by Sno01** [comment]
Kurz mal alles Durchgegangen.
Es betrifft tatsächlich nur die Quadratischen Brillen.

Ich hab Morello als Zeus Objekt hinzugefügt und ihm in Zeus alle Uniformen angezogen. Er hatte dabei de Brille auf und konnte mir immer sagen wann sie da ist und wann nicht.
Ich hab Uniformen nach Mods sortiert. 

Sichtbar ist die Brille bei:
-Vanilla (alle)
-R3F
-FFAA
-Tacs Uniform by Pomigit, Jonpas (Außer der VIP Anzug)
-BAF (Außer Crewman Coveralls RTR)
-BWA3 (Außer Overall Flecktarn, Tropentarn, Helipilot)

Verschwunden war die Brille bei:
-RHS
-RHS Gref
-VIP Anzug
-RHSSAF

Der Rest war Gemischt:

-RHS (Mit Dem Weißen Stern im Zahnrad auf Blauem Grund)
-Projekt Opfor
-RDS Uniforms
-PBW
-SKN 

Ich habe das gefühl das es ein Vanilla Problem ist. Falls du noch ne Idee hast was ich einfach testen kann lass es mich wissen.

**Comment by BAVerrecus** [comment]
es ist leider in der tat ein vanilla problem. hab das jetzt getestet da kann ich leider nix tun, außer zu hoffen dass der tank dlc das ganze eventuell löst. :( sry
