### ISSUE TITLE
Zeus Problem 

### ISSUE THREAD

**Issue by NTF-Parrot** [BAVerrecus/NTF-Modset#33]
Servus BA , wie mir so eben mitgeteilt worden ist, scheint es wieder Probleme mit dem Zeus Modul zu geben. 

1. Bei Martins Mission am 20.3 ging laut Aussage von Morello Zeus nicht 
2. Heute auf dem Maptestserver , keine Möglichkeit in Zeus zu gelangen

**Comment by BAVerrecus** [comment]
nach einigem testen kann ich mittlerweile sagen, wenn alles richtig eingestellt ist und man nicht in zeus reinkommt, muss man etwas warten. mit "etwas" ist "bis zu 5 minuten" gemeint. in den fällen wo das ganze passiert wird die initialisierung nur hinausgezögert. gründe dafür können scripte aber auch loadlouts sein die am beginn der mission durchlaufen und die einfach vor der initialisierung des zeus moduls gereit werden.

deswegen issue closed.
