### ISSUE TITLE
Special Modset 

### ISSUE THREAD

**Issue by StephanPe** [BAVerrecus/NTF-Modset#36]
1. Beim öffnen des Editors kommt bei mir immer folgende Fehlermeldung 
       [https://picload.org/view/dapdglli/20180401114435_1.jpg.html](url)

2. Beim aufbauen mancher Helis kommt folgende Fehlermeldung
       [https://picload.org/view/dapdglwa/20180401121041_1.jpg.html](url)

3. Wenn die Artillerie schießt (Player oder AI) kommt eine fehlermeldung (z.B. bei der D30 122mm Howitzen)
       [https://picload.org/view/dapdgcra/20180329161230_1.jpg.html](url)

**Comment by BAVerrecus** [comment]
zu allererst mal, du startest das komplette special modset. das geht nicht. entweder vietnam ODER WWII ODER SciFi.

1. ist bekannt, macht nichts kaputt. ist nur ein fehlendes inventar icon.
2. auch das ist bekannt. macht auch nichts kaputt. kann sein dass das april update den fehler behabt. mal bis mittwoch warten und dann nochmal überprüfen pls.
3. blastcore fehler. wird mit dem april update behoben werden.

**Comment by BAVerrecus** [comment]
ich wollte das issue garnicht schließen :S

**Comment by BAVerrecus** [comment]
okay, 2 und 3 behoben, 1 macht nix kaputt. deshalb closed
