### ISSUE TITLE
Steuerbarer Fallschirm

### ISSUE THREAD

**Issue by StephanPe** [BAVerrecus/NTF-Modset#37]
Fallschirm auf dem Rücken bewegt sich anders wie der Spieler und/oder verursacht andere Fehler 
[https://picload.org/view/dapdgidw/20180327202406_1.jpg.html](url)

**Comment by BAVerrecus** [comment]
mehr infos pls. am besten das benutzte loadout posten pls.
und eine genaue beschreibung was du getan hast damit ich das reproduzieren kann.

**Comment by BAVerrecus** [comment]
und noch ne frage, passiert das lokal oder am server oder beides?

**Comment by StephanPe** [comment]
das ist bei der Freifallausbildung auf dem Übungsplatzserver vorgekommen und mehrere Spieler hatten solche fehler

**Comment by BAVerrecus** [comment]
okay, das wird ein wenig aufwendiger.
ist notiert, mal sehen was sich finden und dann tun lässt.

**Comment by BAVerrecus** [comment]
Bisher nicht reproduzierbar, die letzte Mission in der das Feature genutzt wurde (3.4.) funktionierte auch fehlerfrei.
Issue bleibt vorerst noch offen.

**Comment by BAVerrecus** [comment]
ich denke dieses issue kann geschlossen werden, feature wurde immer wieder benutzt und bug ist nicht wieder aufgetreten.
