### ISSUE TITLE
Grafikfehler

### ISSUE THREAD

**Issue by StephanPe** [BAVerrecus/NTF-Modset#38]
Manche Items z.B. Red Dot oder Rucksäcke haben Grafikfehler und werden leicht durchsichtig 

[https://picload.org/view/dapdlial/20180401201455_1.jpg.html](url)
[https://picload.org/view/dapdliil/2018040120444](url)

genaue liste welche Items müsste ich noch zusammen stellen hab aber diese woche keine zeit mehr leider

**Comment by BAVerrecus** [comment]
zweiter link funzt nicht

**Comment by StephanPe** [comment]
https://picload.org/view/dapdliil/20180401204443_1.jpg.html

**Comment by BAVerrecus** [comment]
passiert das mit jeder waffe?

**Comment by StephanPe** [comment]
Betrifft nur die RedDots + 3Fach Vergrößerung. Die mod hat ein Puzzleteil als Symbol (Classname: RH_eothhs1) im normalen mod set. Die Waffe spielt dabei keine rolle.

Waffentaschen von ACE (z.B. ace_gunbag_Tan  ,  ace_gunbag) haben auch fehler.

Der TFAR Rucksack (Assault Pack Bussole) löst auch einen fahler aus.
(url)[https://picload.org/view/dapaawal/20180401231350_1.jpg.html](url)

**Comment by BAVerrecus** [comment]
Visiere werden im Mai entfernt. Der Rest ist nicht von meiner seite lösbar.
