### ISSUE TITLE
Redd Wiesel

### ISSUE THREAD

**Issue by Ch3y** [BAVerrecus/NTF-Modset#41]
Der Rückschlag der MK des Wiesel 1 ist so stark, dass bei Dauerfeuer das ganze Fahrzeug weggeschoben wird, bei den APDS Geschossen. Bei den HE-I zieht die Kanone lediglich stark nach oben was man jedoch noch gegenhalten kann. 

Aufgetreten im Editor und im Arsenal

**Comment by BAVerrecus** [comment]
schon bekannt, wird mit dem nächsten update von redd behoben.
