### ISSUE TITLE
Verschwinden und nicht ganz verschwinden der Waffe

### ISSUE THREAD

**Issue by Wecker** [BAVerrecus/NTF-Modset#42]
Bug?: Verschwinden der "Hauptwaffe" nach dem wechseln zu der Pisotle
Wo?: Übungsplatz, Panzergrenadier-Ausbildung von JayJay 
Reproduzierbar?: Ja
Beschreibung: Nachdem die Pistole in die Hand genommen wurde, besteht nicht mehr die Möglichkeit auf das Sturmgewehr zu wechseln. Auch "verschwindet" die Waffe aus dem Inventar. Genutzt wurden folgende Waffen, Sturmgewehr MX (Schwarz) und die Pistole FNX-45 Tactical.

Lösung?: Auf das Sturmgewehr kann trotzdem gewechselt werden, indem die Tastenkombination für den sek. Slot benutzt wird. Oder bei besetzten Slot, kommt nachdem Wechseln auf die sek. Waffe, die Primäre wieder zurück und das Wechseln auf diese Waffe kann mittels Tastenkombination getätigt werden

Notiz: Die Tastenbelegungen wurden gecheckt, Fehler meinerseits können durch den Beleg aus der Lösung 1, dass von der sek. Waffe aus, ohne Probleme mittels der Tastenbelegung gewechselt werden kann, ausgeschlossen werden.
Screenshot: Nicht möglich, bei Nachfrage könnte ein Video gedreht werden.

Bei Fragen und Rückmeldung stehe ich gerne zur Verfügung

MFG Wecker

**Comment by BAVerrecus** [comment]
Das ist kein Bug sondern tatsächlich falsche/nicht eingestellte Tastenbelegung.
Beim letzten Update wurde ein Mod namens "Tactical Weapon Swap" eingeführt. Der hat eigene Tasten. Also entweder die Modtastenbelegung einstellen und die Vanilla entfernen oder umgekehrt.
