### ISSUE TITLE
Kamerabug RHS Little Bird

### ISSUE THREAD

**Issue by TimoNTF** [BAVerrecus/NTF-Modset#44]
Folgender Bug tritt bei der Kamera des Kopiloten auf.

https://1drv.ms/u/s!Ar-cOYubi333cwY208TCCfwt1jU

Wenn man näher reinzoomt wandert der Balken nach Rechts und verschwindet schließlich.

**Comment by BAVerrecus** [comment]
mit der neuen rhs version behoben
