### ISSUE TITLE
Fehlermeldung F16C/D

### ISSUE THREAD

**Issue by TimoNTF** [BAVerrecus/NTF-Modset#45]
Das Tritt beim Laden einer Mission mit F16C/D verbaut.
![107410_20180531163907_1](https://user-images.githubusercontent.com/33878303/40854900-2bb4f5b6-65d3-11e8-959d-4228c579dd58.png)

Ich glaube aber das hat damit zu tun das das Flugzeug unsere TFAR Dev Version nicht unterstützt.

**Comment by BAVerrecus** [comment]
das ist richtig. die f16 hat im cockpit ne kleine anzeige für die im flugzeugfunk eingestellte frequenz. die function hat sich von 0.9.12 auf die 1.0 testversionen verändert und daher kommt der fehler.
issue wird vorerst mal hinten angestellt, da ohnehin jetzt mal das acre testmonat ansteht. sollten wir zu acre zurückkehren wird das issue wieder aufgegriffen.

**Comment by BAVerrecus** [comment]
da jetzt acre benutzt wird, wandert das issue ins achiv.
