### ISSUE TITLE
TFAR Fehlermeldung im TS bei Mission 01.06.2018 | [Orthac] Co29 Operation Bearclaw   

### ISSUE THREAD

**Issue by wurschtl12** [BAVerrecus/NTF-Modset#46]
Ich bekam mehrfach folgende Meldung im TS gepostet:

TFAR: errorLevel out of bounds! err:7.000000/0.999980

**Comment by BAVerrecus** [comment]
wird vorerst zurück gestellt.
wir starten jetzt mal das acre testmonat und sollten wir danach zu tfar zurückkehren wird das issue wieder aufgegriffen.
bis dahin bleibts zwar geöffnet, wird aber nicht weiter verfolgt.

**Comment by BAVerrecus** [comment]
da jetzt acre benutzt wird, wandert das issue ins achiv.
