### ISSUE TITLE
ACRE Fehlerthread

### ISSUE THREAD

**Issue by BAVerrecus** [BAVerrecus/NTF-Modset#49]
Postet in diesem Thread Fehler von ACRE die euch während des Testmonats auffallen!

**Comment by Stehwahn** [comment]
Problem bei ACRE, das ich bei TFAR so nicht hatte (oder es ist mir einfach nur nicht aufgefallen): Wenn Arma grade gut Krach macht, z.B. wegen Munitionsbrand, wird die Sprachausgabe der Mitspieler **_sehr_** leise.
Kein ACRE Problem an sich, eher ein Windowsproblem, sollte meiner Meinung nach trotzdem aufgeführt werden, falls noch jemand dieses Problem erfährt:

Schuld daran ist offenbar der Exklusive Modus von Windows. Hacken bei der Soundquelle der Wahl rausmachen, und das Problem ist behoben.:
![grafik](https://user-images.githubusercontent.com/16347333/41182894-00e0321a-6b78-11e8-92a0-08ea07a4e91f.png)

**Comment by TimoNTF** [comment]
Heute ist mir aufgefallen das die Intercom Lautstärke nicht immer gespeichert wird nach wiedereinsteigen in den Panzer. Ist am Anfang der heutigen Mission 3 mal aufgetreten, konnte ich allerdings später nicht mehr reproduzieren.

**Comment by TimoNTF** [comment]
Wir hatten kein Interkom aufn Übungsplatz irgendwie Funkgerät hinten konnte man nehmen

das sind die genutzen fahrzeuge falls wichtig.
nh90
und ch130

aber sonst verständigung in großen höhen war besser als in tfar

bzw 2 man konnte ich nicht sehen und höheren

**Comment by TimoNTF** [comment]
Ebenso sind bei Morello schon 2 mal der Fehler aufgetreten das er Leute nicht sieht und nicht hören kann da sie unsichtbar wurden.

**Comment by TimoNTF** [comment]
Funkgeräte Reichweitenbegrenzung funktioniert in der Luft nicht.

**Comment by TimoNTF** [comment]
Funkgeräte Reichweite funktioniert in Luftfahrzeugen nicht. Es kommt auch zu komischen abhackern und einsekündigem schlechtem empfang bis es dann wieder normal kommt

**Comment by TimoNTF** [comment]
Anmerkung: Funkgeräte Reichweite funktioniert gar nicht. Getestet am Übungsplatz bei der Freifaller Ausbildung. Benutztes Funkgerät 152
