### ISSUE TITLE
ACE Splint und Endheilung - Humpeln trotz Endheilung

### ISSUE THREAD

**Issue by Stehwahn** [BAVerrecus/NTF-Modset#50]
Wenn man mit angelegtem Splint eine Endheilung bekommt, humpelt man wieder, sobald der Splint sich löst:

**Wie festgestellt:**
1. Bein war verletzt, sodass ich nur noch humpeln konnte.
2. Splint angelegt, damit wieder Einsatzbereit
3. Ich habe eine Endheilung bekommen und war damit wieder auf 100% Leben gezaubert
4. Beim Verlegen kam die Meldung "Splint hat sich gelöst und kann wiederverwendet werden"
5. Der Zustand "Humpeln" wurde wieder hergestellt, trotz voriger Endheilung

**Wie umgehen?**
Splint und Endheilung nicht gemeinsam verbauen, bzw. Endheilung für beispielsweise Medevacs in der Basis aufsparen.

**Comment by BAVerrecus** [comment]
wird mit dem nächsten update gefixt sein. modmacher hat es gefixt.
