### ISSUE TITLE
Editorcrash Da Krong

### ISSUE THREAD

**Issue by TimoNTF** [BAVerrecus/NTF-Modset#53]
Beim Laden der Map Da Krong und anschauen der leeren Karte tritt nach etwa einer Minute der Fehler auf das ArmA einfach Crasht. Konnte ich bisher immer reproduzieren. 

RPTs gibts hier: https://1drv.ms/f/s!Ar-cOYubi333dIE8IRmFBXBPXfc

**Comment by BAVerrecus** [comment]
die rpt sagt mir ansich nichts was der fehler wäre.
hat es dann am server funktioniert?
passiert das auch mit nem anderen modset auf dieser map?

**Comment by BAVerrecus** [comment]
ich bin ein dummer pleb. ich hab die map verwechselt.
das problem das du hast liegt an unsung und ist leider bekannt seit dem ersten release. die macher von unsung sehen das nicht ein weil sie selber nie das problem haben und deswegen wird das ganze vermutlich niemals gefixt werden.
wenn es dich tröstet, eine mission mitspielen geht meistens (obwohl es auch da zu abstürzen kommen kann, aber viel weniger häufig als im editor) und auch ich hab manchmal das problem (boaty mcboatface zu bauen war mehr als nur aufwendigt für mich).
sry dass ich da keine besseren news habe...

**Comment by TimoNTF** [comment]
Am Server ist mir gestern Abend 1x das Game gecrasht. Naja mal sehen wie es heute Abend läuft
