### ISSUE TITLE
M1A2SEPv1 Fehlerhafte Fahreransicht

### ISSUE THREAD

**Issue by TimoNTF** [BAVerrecus/NTF-Modset#54]
In der Fahrerperspektive tritt folgender Sicht bug auf. Man kann allerdings rechte Maustaste drücken dann kommt man in die normale Ansicht für die Winkelspiegel. Liegt nach meinem Wissen am Tanks DLC.
![107410_20180710191709_1](https://user-images.githubusercontent.com/33878303/42655221-b111fe30-861b-11e8-9182-22452dbfb81a.png)

![107410_20180710191713_1](https://user-images.githubusercontent.com/33878303/42655226-b79eef2e-861b-11e8-9875-576c94efaefd.png)

**Comment by BAVerrecus** [comment]
gelöst mit dem neuen rhs update.
