### ISSUE TITLE
Modvorschlag: GRAD Trenches

### ISSUE THREAD

**Issue by Rod3o** [BAVerrecus/NTF-Modset#66]
1.) Um welchen Mod handelt es sich? https://steamcommunity.com/sharedfiles/filedetails/?id=1224892496
2.) Hast du den Mod selber getestet? Ja
2.a) Wenn ja, gibt es Bugs? Bisher selber keine gefunden, jedoch gibt es laut Steam Kommentare auf vereinzelten Karten verinzelt Probleme mit den Hitboxen der Gräben
3.) Hast du den Mod zusammen mit unserem Modset getestet? Ja zumindest auf meinen Rechner allein
3.a) Wenn ja, gibt es Bugs? Keine Gefunden
4.) Welche Requirements hat der Mod? ACE
4.a) Haben wir diese Requirements im Modset? (Wenn "nein" gilt es die Fragen nochmal extra für den benötigten Mod auszufüllen) Ja haben wir
5.) Welchen Mehrwert hätte es diesen Mod aufzunehmen? Mehr Immersion bzw. besseres Landschaftsbild bei Nutzung der ACE Gräben
6.) Wie häufig schätzt du die Nutzung des Mods ein? Kommt auf die Missionsbauer an und den Gruppen in wie weit die bei größeren Missionen die Gräben nutzen. Meiner Meinung nach könnte man sie öfters nutzen, inbesondere für Stellungen
7.) Hast du dich in Foren über Fehler und Probleme mit diesem Mod informiert? In gewisser Hinsicht ja, ich bin zumindest die Kommentare einmal durchgegangen. 
7.a) Wenn ja, was ist das Ergebnis? Bisher habe ich jedoch lediglich die Anmerkungen/Auffälligkeiten, die ich aus dem Steam Kommentaren habe entdeckt
8.) Welche Szenarien könntest du dir mit diesem Mod vorstellen? (wenn es
sich um einen Mod handelt der immer wirkt bzw. Gameplaymechaniken
permanent ändert, ist diese Frage zu ignorieren) 
9.) Was gefällt dir besonders gut an dem Mod? Die Gräben fügen sich gut in die verschiedenen Landschaften ein und stechen nicht so wie die Standard Gräben so heraus. Außerdem gibt es hierbei auch Möglichkeiten Fahrzeugstellungen damit zu verbauen, die gut getarnt sind
10.) Was gefällt dir nicht an diesem Mod? 
11.) Warum willst du gerade diesen Mod und nicht einen mit vergleichbarem Inhalt (wenn es denn einen gibt)? Ich kenne derzeit keinen anderen Mod der etwas vergleichbares macht

**Comment by Plato0** [comment]
Modovrschlag angenommen.
