### ISSUE TITLE
Modvorschlag Type 22 MANTA UGV aka How to Modvorschlag

### ISSUE THREAD

**Issue by Sno01** [BAVerrecus/NTF-Modset#8]
Hallo lieber B.A. und hallo liebe Member.

Ich habe einen Mod gefunden der mir gefällt und den ich nun vorschlagen möchte. 
Ich werde diese Gelegenheit nutzen um euch einmal zu zeigen wie ihr einen Mod bestmöglich darstellt und worauf ihr bei Mods achten solltet.

Generell wenn ihr einen Mod findet der euch interessiert Sparrt euch jede mühe ihn zu testen!
Warum? Nun erstmal gilt es herauszufinden welchen Entwicklungsstand der Mod überhaupt hat.
Schaut dabei auf folgende Punkte:

-seit wann gibt es den Mod? In meinem Fall seit 3.Juli im Workshop und im BI Forum. Seit 5.Juli auf Armaholic 
-Ist der Mod aktuell überhaupt Fertig? Oder ist der Mod in Arbeit, oder wurde er abgebrochen ? <- in meinem Fall aktuell
-Welche bekannten Fehler gibt es? Nun das hier ist einer der wichtigsten Punkte der häufig von euch vergessen wird.
Infos darüber bekommt ihr am besten auf der Forum Seite von BI (Bohemia Interactive). Hier kann man sich in ruhe durchlesen was andere User zu dem Mod angeben.
Aber auch die Kommentare im Steam Workshop können Hilfreich sein. Häufig gibt es Probleme nach größeren Updates oder Kompatibilitätsprobleme mit anderen Mods. 
Alles was ihr Negatives über einen Mod findet solltet ihr erwähnen, seit Fair zum Modsetbauer und Kritisiert euren Mod selbst.
Zu guter letzt kommt ihr um einen Test mit unserem Modset nicht Herum: Hierbei solltet ihr euren Mod auf Herz und Nieren Testen. Denkt dabei auch an solche sachen wie ACE, CTab, TFAR,....

Ok ich Fang jetzt mit dem eigentlichen Modvorschlag an wenn mir noch etwas einfällt ergänze ich es. 

1.) Um welchen Mod handelt es sich? Type 22 MANTA UGV, MANTA im Workshop, MANTA im BI Forum <- Gebt ruhig mehrere Quellen an B.A. freut sich wenn er nicht suchen muss

2.) Hast du den Mod selber getestet? Ja im Addons und SciFi Modset <- In diesem Fall denke ich das der Mod in das SciFi Pack passt also teste ich das natürlich auch.

2.a) Wenn ja, gibt es Bugs? Keine Bekannten Fehler auf allen oben genannten Plattformen genannt.

Der Mod ist laut Usern allerdings wohl nur in der OPFOR Fraktion bei CSAT verfügbar. Der Modder hat angegeben das der in der Kategorie CSAT Pazifik zu finden sei, er steht aber auch im Normalen CSAT.
Ich hatte keine Probleme ihn zu finden und zu verbauen weder im Editor noch im Zeus

3.) Hast du den Mod zusammen mit unserem Modset getestet? Siehe 2.

3.a) Wenn ja, gibt es Bugs? Editor und Co waren zufrieden keine Alarmglocken. Die Foren Schweigen ebenfalls Friedlich dahin.

4.) Welche Requirements hat der Mod? Keine

4.a) Haben wir diese Requirements im Modset? (Wenn "nein" gilt es die Fragen nochmal extra für den benötigten Mod auszufüllen) JA weil keine Benötigt

5.) Welchen Mehrwert hätte es diesen Mod aufzunehmen?

Der MANTA ist sehr Futuristisch angehaucht der Modder meinte zwar er sei an das Zeitalter der ArmA 3Units angepasst (ca.2035) Ich würde ihn dennoch eher dem SciFi zuordnen.
Der Manta ist im vergleich zum Stomper ein Traum es macht richtig Spaß ihn zu fahren. Ein UGV passt perfekt in die SciFi Welt und mit seiner Optik löst er den Stomper leicht ab.
Der MAnta ist ein Schwer gepanzertes UGV. In der Modbeschreibung auf Steam erklärt der Modder das dass Fahrzeug eine Moderne Leichtbauweise in verbindung mit Keramik darstellen soll.
Seine Form sei desweiteren sehr effektiv um Schweres Kaliber abzulenken. Beim Beschusstest stellte sich heraus das der MANTA das wohl am stärksten gepanzerte Vehicle ist das ich je in ArmA gesehen habe. Ich empfinde dies als Kritik punkt :/ 
Getestet wurde mit ansteigendem Kaliber auf Reifen, Hülle und Systeme. Schlusslicht waren KPZ Shells ins Gesicht! Der kleine hällt einiges aus aber ist nicht Unzerstörbar. Aber er kann das Door gut Holden!
Diese Eigenschaft legt allerdings nahe das er nicht sehr gut als Gegnerfahrzeug geeignet ist. Er würde Locker einige AT's des Zuges Schlucken und könnte evtl. noch immer Wirken. Ein Genauerer Test hierzu im Multiplayer wäre Sinnvoll.
Eine besondere Eigenschaft liegt im Höhenverstellbaren Chassis des Fahrzeuges. Aus der Vollgedeckten in die Teilgedeckte stellung innerhalb von Sekunden das ist toll!
Einen wirklichen nutzen sehe ich dennoch leider nicht. Der Manta ist wie viele unserer Mods zwar ziemlich Cool aber wenn ich grob Voraus plane wie oft er wohlmöglich eingesetzt wird sehe ich hier keine wirkliche Bereicherung. Diese Entscheidung obliegt B.A.

Zur bewaffnung.

Der MANTA hat ein Gutes .50Cal - 12,7mm welches sich wie jedes andere Kaliber gerne durch alles Bohrt was ihm im Weg Steht.
Als Zweitwaffe hat er 6 oder 8 Mini Spike AT Missles die ins Ziel gelenkt werden können oder via Aufschaltung Ziele Suchen.
Die Zweitwaffe ist definitiv ein weiterer Kritikpunkt für Mich So viel AT ist etwas OP. <- Ihr solltet wirklich Kritisch sein das zeigt B.A. auch das ihr euren Mod nicht nur wollt weil ihr gerade Spitz wie Nachbars Lumpi seid.
Es beweist außerdem euren ausführlichen Test.

6.) Wie häufig schätzt du die Nutzung des Mods ein? Selten :( 

7.) Hast du dich in Foren über Fehler und Probleme mit diesem Mod informiert? Schon angegeben.

7.a) Wenn ja, was ist das Ergebnis? Nur in der OPFOR Fraktion, Sehr stark Gepanzert Schwer bewaffnet= Gefährliche OP Mischung

8.) Welche Szenarien könntest du dir mit diesem Mod vorstellen? (wenn es sich um einen Mod handelt der immer wirkt bzw. Gameplaymechaniken permanent ändert, ist diese Frage zu ignorieren)
Unbemannte Opperationen, INF unterstützung, Verteidigung, Schwere Erstschläge, Aufklärung

9.) Was gefällt dir besonders gut an dem Mod? Es ist ein UGV ich liebe solche technischen Spielereien. Das Höhenverstellbare Chassis ist klasse, Übersichtliche Fahrerposition im Höhenmodus und sehr gute Geländeeigenschaft.

10.) Was gefällt dir nicht an diesem Mod? Zu stark Gepanzert, Nicht in anderen Fraktionen verbaut. Waffensysteme für normalen Gebrauch leicht übertrieben. Design zu Futuristisch für Addons Modset.

11.) Warum willst du gerade diesen Mod und nicht einen mit vergleichbarem Inhalt (wenn es denn einen gibt)? Keine anderen UGV bekannt. (Vanilla ausgeschlossen)

So das war es nun heißt es warten.

Nochmals Prüft euren Mod Gut! und Informiert euch über jeden Negativ Aspekt den er mit sich Bringt. Schönreden hilft euch nicht.  <3

**Comment by BAVerrecus** [comment]
Der Mod läuft fehlerfrei und ist komplett mit ACE kompatibel. Außer der Häufigkeit der Nutzung gibt es eigentlich keinen Grund ihn nicht aufzunehmen.
Allerdings passt er meiner Meinung nach leider wirklich nur ins SciFi Modset und dort wird er auch landen.
