### ISSUE TITLE
Modvorschlag Swiss (Samsung)

### ISSUE THREAD

**Issue by BAVerrecus** [BAVerrecus/NTF-Modset#9]
1.) Um welchen Mod handelt es sich? (Bitte mit Link) steamcommunity.com/sharedfiles…?id=810881254&searchtext= oder armaholic.com/page.php?id=32033&highlight=SWISS
2.) Hast du den Mod selber getestet? Ja
2.a) Wenn ja, gibt es Bugs? Keine gefunden
3.) Hast du den Mod zusammen mit unserem Modset getestet? Ja haben @Jack Reas und Ich zusammen gemacht
3.a) Wenn ja, gibt es Bugs? Keine Gefunden
4.) Welche Requirements hat der Mod? TFAR + ACE
4.a) Haben wir diese Requirements im Modset? (Wenn "nein" gilt es die Fragen nochmal extra für den benötigten Mod auszufüllen) Ja haben wir
5.) Welchen Mehrwert hätte es diesen Mod aufzunehmen? Eine gute neue Waffe in 3 Versionen + neue Uniformen für eine neue Nation
6.) Wie häufig schätzt du die Nutzung des Mods ein? Kommt auf den missionsbauer drauf an, aber 2 Missionsbauer verwenden diese Mod sicher mehrmals :P
7.) Hast du dich in Foren über Fehler und Probleme mit diesem Mod informiert? Keine Fehler in Foren gefunden
7.a) Wenn ja, was ist das Ergebnis?
8.) Welche Szenarien könntest du dir mit diesem Mod vorstellen? (wenn es
sich um einen Mod handelt der immer wirkt bzw. Gameplaymechaniken
permanent ändert, ist diese Frage zu ignorieren) Szenarien wo man die Schweizer Armee verbauen kann, z.b Friendestruppen der UN oder fiktive Szenarie wo die Schweiz nicht neutral ist :whistling: ?(
9.) Was gefällt dir besonders gut an dem Mod? Die Waffe ist sehr gut. Und es bringt uns eine neue Nation ins Modset
10.) Was gefällt dir nicht an diesem Mod? Leider zuwenig ausrüstung, aber die Grund Ausrüstung ist drin
11.) Warum willst du gerade diesen Mod und nicht einen mit vergleichbarem Inhalt (wenn es denn einen gibt)? Es gibt keinen der ansatzweise Orginal getreu ist

**Comment by NTFSamsung** [comment]
Darf man fragen wie es noch damit aussieht?

**Comment by BAVerrecus** [comment]
1. Der Mod wirft schon im Startbildschirm von Arma nen Fehler
2. Die Waffen haben weder ACE noch JR configs
3. Das Equipment ist durch die Bank nur geretextured, kann also missionsseitig eingebaut werden
4. Die Sounds sind alle irgendwie komisch. Mal davon abgesehen dass sie keine tails haben, sind sie unterschiedlich laut. damit meine ich dass schüße für den schützen teilweise so klingen als wäre die waffe ein paar meter weit weg abgefeuert worden.

wegen der vielzahl an problemen deshalb leider nein.
